import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { inventoryApi, analyticsApi, alertsApi, predictionsApi, procurementApi } from "@/lib/api";
import { toast } from "sonner";

// ─── Inventory ────────────────────────────────────────────────────────────────
export function useInventory(params?: object) {
  return useQuery({
    queryKey: ["inventory", params],
    queryFn: () => inventoryApi.list(params).then((r) => r.data),
    keepPreviousData: true,
  });
}

export function useInventoryItem(id: string) {
  return useQuery({
    queryKey: ["inventory-item", id],
    queryFn: () => inventoryApi.get(id).then((r) => r.data),
    enabled: !!id,
  });
}

export function useCreateItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: object) => inventoryApi.create(data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["inventory"] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      toast.success("Item created successfully");
    },
    onError: (e: any) => toast.error(e.response?.data?.detail ?? "Failed to create item"),
  });
}

export function useUpdateItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: object }) => inventoryApi.update(id, data),
    onSuccess: (_, { id }) => {
      qc.invalidateQueries({ queryKey: ["inventory"] });
      qc.invalidateQueries({ queryKey: ["inventory-item", id] });
      toast.success("Item updated");
    },
    onError: (e: any) => toast.error(e.response?.data?.detail ?? "Failed to update item"),
  });
}

export function useDeleteItem() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => inventoryApi.delete(id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["inventory"] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      toast.success("Item deleted");
    },
  });
}

export function useLogUsage() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ itemId, data }: { itemId: string; data: object }) =>
      inventoryApi.logUsage(itemId, data),
    onSuccess: (_, { itemId }) => {
      qc.invalidateQueries({ queryKey: ["inventory"] });
      qc.invalidateQueries({ queryKey: ["inventory-item", itemId] });
      qc.invalidateQueries({ queryKey: ["dashboard"] });
      toast.success("Usage logged");
    },
    onError: (e: any) => toast.error(e.response?.data?.detail ?? "Failed to log usage"),
  });
}

// ─── Analytics ────────────────────────────────────────────────────────────────
export function useDashboard() {
  return useQuery({
    queryKey: ["dashboard"],
    queryFn: () => analyticsApi.dashboard().then((r) => r.data),
    refetchInterval: 60_000,
  });
}

export function useTopItems(days = 30, limit = 10) {
  return useQuery({
    queryKey: ["top-items", days, limit],
    queryFn: () => analyticsApi.topItems(days, limit).then((r) => r.data),
  });
}

export function useDepartmentUsage(days = 30) {
  return useQuery({
    queryKey: ["dept-usage", days],
    queryFn: () => analyticsApi.departmentUsage(days).then((r) => r.data),
  });
}

// ─── Predictions ──────────────────────────────────────────────────────────────
export function useItemPrediction(itemId: string) {
  return useQuery({
    queryKey: ["prediction", itemId],
    queryFn: () => predictionsApi.item(itemId).then((r) => r.data),
    enabled: !!itemId,
    staleTime: 5 * 60_000,
  });
}

export function useBulkPredictions() {
  return useQuery({
    queryKey: ["bulk-predictions"],
    queryFn: () => predictionsApi.bulk().then((r) => r.data),
    staleTime: 5 * 60_000,
  });
}

// ─── Alerts ───────────────────────────────────────────────────────────────────
export function useAlerts(status?: string) {
  return useQuery({
    queryKey: ["alerts", status],
    queryFn: () => alertsApi.list(status ? { status } : {}).then((r) => r.data),
    refetchInterval: 30_000,
  });
}

export function useUnreadNotifications() {
  return useQuery({
    queryKey: ["notifications-unread"],
    queryFn: () => alertsApi.myNotifications(true).then((r) => r.data),
    refetchInterval: 30_000,
  });
}

// ─── Procurement ──────────────────────────────────────────────────────────────
export function useProcurement(status?: string) {
  return useQuery({
    queryKey: ["procurement", status],
    queryFn: () => procurementApi.list(status ? { status } : {}).then((r) => r.data),
  });
}

export function useAutoSuggest() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: () => procurementApi.autoSuggest(),
    onSuccess: (res) => {
      qc.invalidateQueries({ queryKey: ["procurement"] });
      toast.success(`${res.data.created} suggestions generated by AI`);
    },
    onError: () => toast.error("Auto-suggest failed"),
  });
}
